name: Build & Push the workload

on: 
  schedule:
    # midnight on a Monday
    - cron: '0 0 * * 1' 
  workflow_dispatch:
jobs:
  build_workload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Antithesis Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.ANTITHESIS_GAR_KEY }}

    - name: Extract metadata (tags) for Docker
      id: meta-container-image
      uses: docker/metadata-action@v5
      with:
        images: us-central1-docker.pkg.dev/molten-verve-216720/demo-repository/etcd-client
        tags: |
          type=sha
          demo
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        # node count can also be one 
        build-args: |
          GO_VERSION=1.26.1
          CFG_NODE_COUNT=3
        context: .
        file: ./test-template/Dockerfile
        push: true
        tags: ${{ steps.meta-container-image.outputs.tags }}
        labels: ${{ steps.meta-container-image.outputs.labels }}