name: CI

on:
  schedule:
    - cron: '0 1 * * 1' 
  workflow_dispatch:
    inputs:
      duration:
        type: string
        required: false # default set below b/c automated runs don't use this config
        description: Test duration (hours, default 0.5)
      emails:
        type: string
        required: false
        description: Email recipients (default notifies Zulip)
      etcd_version:
        type: choice
        required: false
        description: The version of etcd config to build
        options:
          - all
          - v3.5.8
          - v3.5.5
          - v3.5.0
          - v3.6.3

jobs:
  Antithesis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        etcd_version: ${{ (github.event_name == 'schedule' || github.event.inputs.etcd_version == 'all') && fromJSON('["v3.5.8", "v3.5.5", "v3.5.0", "v3.6.3"]') || fromJSON(format('["{0}"]', github.event.inputs.etcd_version)) }}
    steps:
      - name: Trigger Antithesis
        uses: antithesishq/antithesis-trigger-action@main
        with:
          notebook_name: etcd
          tenant: demo
          username: ${{ secrets.ANTITHESIS_USERNAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GH_PAT }}
<<<<<<< HEAD
          config_image: us-central1-docker.pkg.dev/molten-verve-216720/demo-repository/etcd-config:${{ matrix.etcd_version }}
          description: "[${{ github.repository }}] CI for ${{ github.ref_name }} (commit ${{ github.sha }})"
=======
          config_image: etcd-config:${{ matrix.etcd_version }}
          description: "${{ matrix.etcd_version }} - [${{ github.repository }}] CI for ${{ github.ref_name }} (commit ${{ github.sha }})"
>>>>>>> origin/main
          email_recipients: ${{ github.event.inputs.emails || secrets.ZULIP_REPORT_EMAIL }}
          additional_parameters: |-
            custom.duration=${{ github.event.inputs.duration || '0.5' }}
            custom.etcd_version=${{ matrix.etcd_version }}
